---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.13.5-alpine3.10
  commands:
  - go build --ldflags "-w -s" -o linker cmd/main.go

...
